#!/bin/bash
echo "*******************************************"
echo "**                                       **"
echo "**               SkipAdsTV               **"
echo "**  Tiện ích bỏ qua quảng cáo YoutubeTV  **"
echo "**                                       **"
echo "*******************************************"
echo "*                 Linor                   *"
echo "*******************************************"
sleep 3

# Check if the virtual environment already exists
if [ ! -d "venv" ]; then
    # Create a virtual environment
    python3 -m venv venv
fi

# Activate the virtual environment
source venv/bin/activate

# Check if start.py exists and install necessary packages
if [ ! -f start.py ]; then
    sudo apt-get update
    sudo apt-get --assume-yes upgrade
    sudo apt-get install unzip python3 python3-pip wget -y
    wget -O skip.zip "https://github.com/quydang04/TVADS/raw/main/skip.zip"
    unzip skip.zip
    rm skip.zip
    mkdir -p ~/.local/share/SkipAdsTV
    python3 -m pip install -r re.txt
fi

# Run the start.py script
if [ ! -f re ]; then
    python3 start.py -s
fi

while [ -f re ]; do
    python3 start.py
    break
done
